//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaWeb.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo
    {
        public int cod_grupo { get; set; }
        public string nombre { get; set; }
        public int capacidad { get; set; }
        public string tipo_ciclo { get; set; }
        public int cod_asig { get; set; }
    
        public virtual pensum pensum { get; set; }
    }
}
